image:
- Visual Studio 2017
#- Ubuntu

stack: python 3.7

environment:
  PY_DIR: C:\Python37-x64

clone_depth: 3

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install: pip install -e .[tests,io]

test_script: pytest

